"""Karıştırma (EA) güvenlik tavanları — TX/Test tavanlarından ayrı."""

from sdr_console.tx.constants import (
    ABSOLUTE_MIN_ATTENUATION_DB,
    DEFAULT_TX_FREQ_HZ,
    PLUTO_DUPLEX_SAMPLE_RATE_HZ,
    PLUTO_MIN_TX_RF_BANDWIDTH_HZ,
)

# Jam yolu TX/Test 40 dB tabanını aşabilir; mutlak taban 10 dB.
MIN_JAM_ATTENUATION_DB = ABSOLUTE_MIN_ATTENUATION_DB
DEFAULT_JAM_ATTENUATION_DB = MIN_JAM_ATTENUATION_DB

MAX_JAM_DURATION_S = 15.0
DEFAULT_JAM_DURATION_S = 5.0
MIN_JAM_DURATION_S = 0.10

DEFAULT_JAM_FREQ_HZ = DEFAULT_TX_FREQ_HZ
DEFAULT_JAM_BANDWIDTH_HZ = PLUTO_DUPLEX_SAMPLE_RATE_HZ
MIN_JAM_BANDWIDTH_HZ = PLUTO_MIN_TX_RF_BANDWIDTH_HZ

# CW yok; baraj gürültüsü tepe ölçeklemeden önce bu RMS'e çekilir.
BARRAGE_NOISE_RMS = 0.85
